apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    klusvoorjou.service: apigateway
  name: apigateway
  namespace: klusvoorjou
spec:
  replicas: 1
  selector:
    matchLabels:
      klusvoorjou.service: apigateway
  template:
    metadata:
      labels:
        klusvoorjou.service: apigateway
    spec:
      containers:
      - name: klusvoorjou-apigateway
        image: youris30/kvj_apigateway
        imagePullPolicy: Always
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: dev
          - name: ASPNETCORE_URLS
            value: http://+:80 
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "20Mi"
            cpu: "100m"        
      hostname: apigateway
      restartPolicy: Always
