apiVersion: v1
kind: Service
metadata:
  labels:
    klusvoorjou.service: apigateway
  name: apigateway
  namespace: klusvoorjou
spec:
  type: LoadBalancer
  selector:
    klusvoorjou.service: apigateway
  ports:
  - name: "http"
    port: 5000
    targetPort: 80
  - name: "https"
    port: 5001
    targetPort: 443