apiVersion: v1
kind: Service
metadata:
  labels:
    klusvoorjou.service: authservice
  name: authservice
  namespace: klusvoorjou
spec:
  type: LoadBalancer
  selector:
    klusvoorjou.service: authservice
  ports:
  - name: "http"
    port: 5024
    targetPort: 80
  - name: "https"
    port: 5025
    targetPort: 443