apiVersion: v1
kind: PersistentVolume
metadata:
  name: authservice-db-volume
  namespace: klusvoorjou
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-db-pvc
  namespace: klusvoorjou
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
