apiVersion: v1
kind: Service
metadata:
  labels:
    klusvoorjou.service: authservice-db
  name: authservice-db
  namespace: klusvoorjou
spec:
  type: ClusterIP
  ports:
  - name: "authservice-db"
    port: 5201
    targetPort: 3306
  selector:
    klusvoorjou.service: authservice-db
